---
# tasks file for bamboo

- name: stop service if upgrade
  service: name=bamboo state=stopped
  when: bamboo_upgrade == true
  notify: restart bamboo
  tags: bamboo

- name: remove legacy binary if upgrade
  file:
    path={{ item.path }}
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
    state={{ item.state }}
  with_items:
    - { path: "{{ bamboo_catalina }}", owner: "{{ bamboo_user }}", group: "{{ bamboo_user }}", mode: '0755', state: 'absent' }
  when: bamboo_upgrade == true
  notify: restart bamboo
  tags: bamboo

- name: create system user
  user:
    name={{ bamboo_user }}
    password={{ bamboo_pass }}
    home={{ bamboo_home }}
    system=yes
    shell=/bin/bash
  notify: restart bamboo
  tags: bamboo

- name: prepare files
  file:
    path={{ item.path }}
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
    state={{ item.state }}
  with_items:
    - { path: "{{ bamboo_catalina }}", owner: "{{ bamboo_user }}", group: "{{ bamboo_user }}", mode: '0755', state: 'directory' }
  notify: restart bamboo
  tags: bamboo

- name: download package
  get_url:
    url={{ bamboo_url }}
    dest={{ bamboo_archive }}
    sha256sum={{ bamboo_sha256 }}
  notify: restart bamboo
  tags: bamboo

- name: unarchive package
  shell: tar zxvf {{ bamboo_archive }} -C {{ bamboo_catalina }} --strip-components=1; chown -Rf {{ bamboo_user }}:{{ bamboo_user }} {{ bamboo_catalina }}
  args:
    creates: "{{ bamboo_catalina }}/bin/start-bamboo.sh"
  notify: restart bamboo
  tags: bamboo

- name: copy templates
  template:
    src={{ item.src }}
    dest={{ item.dest }}
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
  with_items:
    - { src: 'etc/init.d/bamboo.j2', dest: '/etc/init.d/bamboo',  owner: 'root', group: 'root', mode: '0755' }
    - { src: 'usr/share/bamboo/bin/setenv.sh.j2', dest: "/{{ bamboo_catalina }}/bin/setenv.sh", owner: "{{ bamboo_user }}", group: "{{ bamboo_user }}", mode: '0644' }
    - { src: 'usr/share/bamboo/conf/server.xml.j2', dest: "/{{ bamboo_catalina }}/conf/server.xml", owner: "{{ bamboo_user }}", group: "{{ bamboo_user }}", mode: '0644' }
  notify: restart bamboo
  tags: bamboo

- name: enable service
  service: name=bamboo enabled=yes
  notify: restart bamboo
  tags: bamboo
